### ISSUE TITLE
Avoid creating s3 buckets unless explicitly asked to

### ISSUE THREAD

**Issue by ferrouswheel** [aws/aws-sdk-pandas#1863] opened 2022-12-13 19:49 UTC
I was very surprised when awswrangler created a new bucket for the results of an athena query.

I was also surprised that it created a bucket without encryption and that allowed s3 objects to be public.

Please make it very explicit that awswrangler will create these top level resources. By default, I believe awswrangler should not do this. If it must create s3 buckets, please at least create them with secure and best-practice defaults.

A better experience would be to use a default bucket, and error if it doesn't exist.

If you still want to make it easy for people who don't mind buckets being made as side-effect of an sql query, then have a flag "create_bucket" that can be true/false.

Thanks for your time and effort on this library.

**Comment by jaidisido** [comment] 2022-12-15 13:47
Thanks @ferrouswheel, the only reason the library creates an S3 bucket is because Athena itself used to do it too. You can see from issue #1707 that some people found it useful. The bucket was created in a similar manner to how it was created by the service. It seems that this is not done anymore, so we will work on removing this behaviour as well. I am closing this as it's a duplicate of the issue aforementioned.

**Closed by jaidisido** 2022-12-15 13:47 UTC
Labels: feature
