### ISSUE TITLE
create_cluster default configuration does not work for EMR >6.8.0 

### ISSUE THREAD

**Issue by rmcsqrd** [aws/aws-sdk-pandas#2077] opened 2023-03-01 05:18 UTC
### Describe the bug

Per https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-configure.html EMR >=6.8.0 uses `spark-log4j2`.  The default `configurations` value for `emr.create_cluster` implicitly assumes that the EMR version being used is <6.8.0 via https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/emr.py#L157-L165. 

Full stacktrace is:

```
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
/Users/rio.mcmahon/dev/reserv_pred/aux/junk.ipynb Cell 6 in <cell line: 2>()
      1 import awswrangler as wr
----> 2 cluster_id = wr.emr.create_cluster(
      3     subnet_id='REDACTED',
      4     cluster_name='REDACTED',
      5     emr_release='emr-6.9.0',
      6 )

File /opt/anaconda3/envs/prefect_env/lib/python3.9/site-packages/awswrangler/emr.py:706, in create_cluster(subnet_id, cluster_name, logging_s3_path, emr_release, emr_ec2_role, emr_role, instance_type_master, instance_type_core, instance_type_task, instance_ebs_size_master, instance_ebs_size_core, instance_ebs_size_task, instance_num_on_demand_master, instance_num_on_demand_core, instance_num_on_demand_task, instance_num_spot_master, instance_num_spot_core, instance_num_spot_task, spot_bid_percentage_of_on_demand_master, spot_bid_percentage_of_on_demand_core, spot_bid_percentage_of_on_demand_task, spot_provisioning_timeout_master, spot_provisioning_timeout_core, spot_provisioning_timeout_task, spot_timeout_to_on_demand_master, spot_timeout_to_on_demand_core, spot_timeout_to_on_demand_task, python3, spark_glue_catalog, hive_glue_catalog, presto_glue_catalog, consistent_view, consistent_view_retry_seconds, consistent_view_retry_count, consistent_view_table_name, bootstraps_paths, debugging, applications, visible_to_all_users, key_pair_name, security_group_master, security_groups_master_additional, security_group_slave, security_groups_slave_additional, security_group_service_access, docker, extra_public_registries, spark_log_level, spark_jars_path, spark_defaults, spark_pyarrow, custom_classifications, maximize_resource_allocation, steps, custom_ami_id, step_concurrency_level, keep_cluster_alive_when_no_steps, termination_protected, auto_termination_policy, tags, boto3_session)
    704 args: Dict[str, Any] = _build_cluster_args(**locals())
    705 client_emr: boto3.client = _utils.client(service_name="emr", session=boto3_session)
--> 706 response: Dict[str, Any] = client_emr.run_job_flow(**args)
    707 _logger.debug("response: \n%s", pprint.pformat(response))
    708 return cast(str, response["JobFlowId"])

File /opt/anaconda3/envs/prefect_env/lib/python3.9/site-packages/botocore/client.py:530, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    526     raise TypeError(
    527         f"{py_operation_name}() only accepts keyword arguments."
    528     )
    529 # The "self" in this scope is referring to the BaseClient.
--> 530 return self._make_api_call(operation_name, kwargs)

File /opt/anaconda3/envs/prefect_env/lib/python3.9/site-packages/botocore/client.py:960, in BaseClient._make_api_call(self, operation_name, api_params)
...
--> 960     raise error_class(parsed_response, operation_name)
    961 else:
    962     return parsed_response

ClientError: An error occurred (ValidationException) when calling the RunJobFlow operation: Classification 'spark-log4j' is not valid for parent classification 'null'.

```

### How to Reproduce

```python
import awswrangler as wr
cluster_id  = wr.emr.create_cluster(
    subnet_id='you_subnet_id',
    cluster_name='your_cluster_name',
    emr_release='emr-6.9.0'
)
```

### Expected behavior

I expected the cluster to spin up - the snippets break when using EMR version 6.9.0 (discovered this while upgrading my cluster from 6.5.0; setting `emr_release='emr-6.5.0'` successfully spins up a cluster. )

### OS

MacOS 12.2.1 and Debian 11 bullseye (in docker)

### Python version

3.9

### AWS SDK for pandas version

2.19.0

**Comment by rmcsqrd** [comment] 2023-03-01 05:21
I am happy to issue a PR but would like guidance on how to proceed. My inclination is to include some sort of logic that checks the EMR version then sets the log4j configuration accordingly (probably in-line [here](https://github.com/aws/aws-sdk-pandas/blob/main/awswrangler/emr.py#L157-L165)) - I want someone familiar with the projects go ahead before I start work on that though if possible.

**Comment by jaidisido** [comment] 2023-03-01 09:21
I think this might be a duplicate of https://github.com/aws/aws-sdk-pandas/issues/1938. It has been fixed and will be available in the next release

**Closed by jaidisido** 2023-03-01 09:21 UTC
Labels: bug

**Comment by rmcsqrd** [comment] 2023-03-02 00:37
This is indeed a duplicate - didn't see it in the closed issues tag.
