### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by Thijss** [aws/aws-sdk-pandas#1802] opened 2022-11-28 08:41 UTC
Currently when using pip or poetry to install `awswrangler`, I am getting:
> awswrangler (2.17.0) requires Python >=3.7.1,<3.11

**Describe the solution you'd like**
I would like teo able to install `awswrangler` on Python 3.11

**Comment by jaidisido** [comment] 2022-11-28 09:28
Duplicate of https://github.com/aws/aws-sdk-pandas/issues/1714

**Closed by jaidisido** 2022-11-28 09:28 UTC
Labels: feature
