### ISSUE TITLE
s3.to_parquet writes corrupt files on rare occasions

### ISSUE THREAD

**Issue by marwan116** [aws/aws-sdk-pandas#2066] opened 2023-02-27 21:36 UTC
### Describe the bug

@alexifm and I found that on rare occasions calls to wr.s3.to_parquet lead to creating corrupt parquet files

We are not exactly sure why this occurs - whether it is an s3 connection issue, a bad handling of threads or a deeper pyarrow issue, or something else....

Here is a sample traceback that we bump into when trying to read the corrupt file (exact file path redacted)

Note: re-running s3.to_parquet resolves the issue in our case

```python
In [5]: import awswrangler as wr
   ...: import pandas as pd

In [6]: wr.s3.read_parquet("s3://my-bucket/path/type=L2/")
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 wr.s3.read_parquet("s3://my-bucket/path/type=L2/")

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/awswrangler/s3/_read_parquet.py:777, in read_parquet(path, path_root, path_suffix, path_ignore_suffix, version_id, ignore_empty, ignore_index, partition_filter, columns, validate_schema, chunked, dataset, categories, safe, map_types, use_threads, last_modified_begin, last_modified_end, boto3_session, s3_additional_kwargs, pyarrow_additional_kwargs)
    769     return _read_parquet_chunked(
    770         paths=paths,
    771         chunked=chunked,
   (...)
    774         **args,
    775     )
    776 if len(paths) == 1:
--> 777     return _read_parquet(
    778         path=paths[0],
    779         version_id=versions[paths[0]] if isinstance(versions, dict) else None,
    780         **args,
    781     )
    782 if validate_schema is True:
    783     _validate_schemas_from_files(
    784         paths=paths,
    785         version_ids=versions,
   (...)
    789         s3_additional_kwargs=s3_additional_kwargs,
    790     )

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/awswrangler/s3/_read_parquet.py:540, in _read_parquet(path, version_id, columns, categories, safe, map_types, boto3_session, dataset, validate_schema, path_root, s3_additional_kwargs, use_threads, pyarrow_additional_kwargs)
    537 pyarrow_args = _set_default_pyarrow_additional_kwargs(pyarrow_additional_kwargs)
    538 boto3_session = _utils.ensure_session(boto3_session)
    539 return _arrowtable2df(
--> 540     table=_read_parquet_file(
    541         path=path,
    542         columns=columns,
    543         categories=categories,
    544         boto3_session=boto3_session,
    545         s3_additional_kwargs=s3_additional_kwargs,
    546         use_threads=use_threads,
    547         version_id=version_id,
    548         validate_schema=validate_schema,
    549         pyarrow_additional_kwargs=pyarrow_args,
    550     ),
    551     categories=categories,
    552     safe=safe,
    553     map_types=map_types,
    554     use_threads=use_threads,
    555     dataset=dataset,
    556     path=path,
    557     path_root=path_root,
    558     timestamp_as_object=pyarrow_args["timestamp_as_object"],
    559 )

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/awswrangler/s3/_read_parquet.py:480, in _read_parquet_file(path, columns, categories, boto3_session, s3_additional_kwargs, use_threads, validate_schema, version_id, pyarrow_additional_kwargs)
    470 s3_block_size: int = 20_971_520 if columns else -1  # One shot for a full read otherwise 20 MB (20 * 2**20)
    471 with open_s3_object(
    472     path=path,
    473     mode="rb",
   (...)
    478     boto3_session=boto3_session,
    479 ) as f:
--> 480     pq_file: Optional[pyarrow.parquet.ParquetFile] = _pyarrow_parquet_file_wrapper(
    481         source=f,
    482         read_dictionary=categories,
    483         coerce_int96_timestamp_unit=pyarrow_args["coerce_int96_timestamp_unit"],
    484     )
    485     if validate_schema and pq_file and columns:
    486         pq_file_columns: List[str] = pq_file.schema.names

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/awswrangler/s3/_read_parquet.py:42, in _pyarrow_parquet_file_wrapper(source, read_dictionary, coerce_int96_timestamp_unit)
     40 try:
     41     try:
---> 42         return pyarrow.parquet.ParquetFile(
     43             source=source, read_dictionary=read_dictionary, coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
     44         )
     45     except TypeError as ex:
     46         if "got an unexpected keyword argument" in str(ex):

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/pyarrow/parquet.py:230, in ParquetFile.__init__(self, source, metadata, common_metadata, read_dictionary, memory_map, buffer_size, pre_buffer, coerce_int96_timestamp_unit)
    226 def __init__(self, source, metadata=None, common_metadata=None,
    227              read_dictionary=None, memory_map=False, buffer_size=0,
    228              pre_buffer=False, coerce_int96_timestamp_unit=None):
    229     self.reader = ParquetReader()
--> 230     self.reader.open(
    231         source, use_memory_map=memory_map,
    232         buffer_size=buffer_size, pre_buffer=pre_buffer,
    233         read_dictionary=read_dictionary, metadata=metadata,
    234         coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
    235     )
    236     self.common_metadata = common_metadata
    237     self._nested_paths_by_prefix = self._build_nested_paths()

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/pyarrow/_parquet.pyx:991, in pyarrow._parquet.ParquetReader.open()

File ~/.pyenv/versions/3.8.5/envs/pyinfima/lib/python3.8/site-packages/pyarrow/error.pxi:99, in pyarrow.lib.check_status()

ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```

### How to Reproduce

Unfortunately, we are not able to reproduce this error, it occurs in rare cases.

### Expected behavior

We expect s3.to_parquet to either be robust enough not to produce a corrupt file, or to throw an exception if it produces corrupt parquet files. The current behavior is a silent failure which is far from ideal.

### OS

Debian GNU/Linux 10

### Python version

3.8.5

### AWS SDK for pandas version

2.16.1

**Comment by marwan116** [comment] 2023-02-27 22:06
Here is a simplified version of the `s3.to_parquet` call that we are performing

```
import pandas as pd
import awswrangler as wr

df = pd.DataFrame({
    "type_col": pd.Categorical(["1"] * 5, categories=["1"]),
    "dt_col": pd.date_range("2020-01-01", periods=5),
    "int_col": [1, 2, 3, 4, 5],
    "float32_col": [1.0, 2.0, 3.0, 4.0, 5.0],
    "float64_col": [1.0, 2.0, 3.0, 4.0, 5.0],
})


wr.s3.to_parquet(
    df=df,
    path="s3://bucket/path/",
    compression="snappy",
    dataset=True,
    mode="overwrite_partitions",
    partition_cols=["type_col"],
)

```

**Comment by marwan116** [comment] 2023-02-28 00:55
One thing that is worth pointing out is that the corrupt file is significantly smaller than the non-corrupt file. In our case, the corrupt file size was 5.8 MB whereas the non-corrupt file ended up being 7.4 MB in size

**Comment by jaidisido** [comment] 2023-03-02 10:00
As you can appreciate it's pretty difficult for us to determine what goes wrong here given how rare this seems to be. It can be any number of issues from networking to arrow itself as you mentioned, and I don't see anything wrong with your code. Have you tried enabling [logging](https://github.com/aws/aws-sdk-pandas#logging) so that we can trace back what might have occurred for these corrupted files?

**Comment by marwan116** [comment] 2023-03-02 13:36
Fair suggestion, I will enable logging and update on this thread if/when this re-occurs

**Comment by marwan116** [comment] 2023-03-04 19:23
So we enabled logging and here is what we found:

This issue crops up when we have data pipelines that fan out to many workers writing to S3 concurrently.

We compared the logs between two workers:
- worker1: which wrote the corrupt parquet file
- worker2: wrote a perfectly ok parquet file.

We found that worker1 is submitting a `_to_parquet` task twice with the same args, whereas worker2 only submits the `_to_parquet` task once.

Based on the logs and the duplicate call to `to_parquet` - what seems to be happening is an improper clean-up after a first failed attempt

We are thinking to temporarily resolving the i
ssue by disabling concurrent writes - will update you if this is indeed an effective temporary workaround.

Attached are worker 1 and worker 2 logs
- [worker1_logs.csv](https://github.com/aws/aws-sdk-pandas/files/10889459/worker1_logs.csv)
- [worker2_logs.csv](https://github.com/aws/aws-sdk-pandas/files/10889460/worker2_logs.csv)

**Comment by marwan116** [comment] 2023-03-06 04:46
So setting `use_threads=False` did not resolve things, but it seems to have uncovered the issue.

The call to `writer.close()` and in turn s3obj.close() is now to be failing with a `botocore.exceptions.EndpointConnectionError`. 

So it seems that `use_threads=True` has the indirect effect of retrying the write but without proper closing of the resource leading to a corrupt file 

```python
 File "/usr/local/lib/python3.8/site-packages/infima/toolkit/data/parquet/io.py", line 181, in _to_parquet_s3
    wr.s3.to_parquet(
  File "/usr/local/lib/python3.8/site-packages/awswrangler/_config.py", line 461, in wrapper
    return function(**args)
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_parquet.py", line 637, in to_parquet
    paths, partitions_values = _to_dataset(
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_dataset.py", line 228, in _to_dataset
    paths, partitions_values = _to_partitions(
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_dataset.py", line 87, in _to_partitions
    proxy.write(
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_concurrent.py", line 48, in write
    self._results += func(boto3_session=boto3_session, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_parquet.py", line 188, in _to_parquet
    writer.write_table(table)
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_write_parquet.py", line 75, in _new_writer
    writer.close()
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_fs.py", line 588, in open_s3_object
    s3obj.close()
  File "/usr/local/lib/python3.8/site-packages/awswrangler/s3/_fs.py", line 474, in close
    _utils.try_it(
  File "/usr/local/lib/python3.8/site-packages/awswrangler/_utils.py", line 343, in try_it
    return f(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 711, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 731, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 183, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 305, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 292, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "/usr/local/lib/python3.8/site-packages/botocore/retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 249, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 321, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 434, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://infima-data-xxxx.s3.us-west-2.amazonaws.com//c06866fd-2153-464d-8796-004d225a12ca.snappy.parquet"
```

**Comment by kukushking** [comment] 2023-03-07 17:39
@marwan116 I am not able to reproduce this just yet, but a couple of pointers to try in the meantime:
1. Enable `debug` logging level. This will provide a bit more visibility, specifically what happens with opening/closing objects. Would be great if you could share worker logs during the time the issue happens as well. 
2. Update from `2.16.1` version to the latest release `2.20.0`. There were quite a few changes to the related code so there is a chance the bug could be fixed.
3. Double check endpoint config of worker 1 `https://infima-data-xxxx.s3.us-west-2.amazonaws.com//c06866fd-2153-464d-8796-004d225a12ca.snappy.parquet` Is there a chance it is concurrently modified?

**Comment by marwan116** [comment] 2023-03-07 18:55
@kukushking thank you for your response on this:

> Enable debug logging level. This will provide a bit more visibility, specifically what happens with opening/closing objects. Would be great if you could share worker logs during the time the issue happens as well.

Please see my earlier [comment here] where I share the wrangler debug logs of two workers, one which produces a corrupt parquet file and another which produces a non-corrupt file.

> Double check endpoint config of worker 1 https://infima-data-xxxx.s3.us-west-2.amazonaws.com//c06866fd-2153-464d-8796-004d225a12ca.snappy.parquet Is there a chance it is concurrently modified?

No chance


> Update from 2.16.1 version to the latest release 2.20.0. There were quite a few changes to the related code so there is a chance the bug could be fixed.

I am sorry this is a bit non-trivial for us to do at the moment. For now our temporary workaround is the following:
- we set `use_threads=False` in the to_parquet call
- we add our own retry handler to handle the `botocore.exceptions.EndpointConnectionError`

**Comment by kukushking** [comment] 2023-03-08 12:46
>we add our own retry handler to handle the botocore.exceptions.EndpointConnectionError

You can try to increase boto3 retries as below. 

```
import awswrangler as wr
import botocore
wr.config.botocore_config = botocore.config.Config(
    retries={"max_attempts": 10},
)
```
Ultimately I would advice to drill down into the root cause - judging by the logs it looks like there is an intermittent error connecting to the endpoint.  By the way, note the endpoint contains a **//**  `https://infima-data-xxxx.s3.us-west-2.amazonaws.com//c06866fd-2153-464d-8796-004d225a12ca.snappy.parquet` that is perhaps causing an issue. Due to its intermittent nature, there may be something in your worker that is updating endpoint value concurrently, causing the worker to occasionally make a call to an invalid endpoint.

**Comment by marwan116** [comment] 2023-03-08 13:49
> . By the way, note the endpoint contains a // https://infima-data-xxxx.s3.us-west-2.amazonaws.com//c06866fd-2153-464d-8796-004d225a12ca.snappy.parquet that is perhaps causing an issue

Apologies, this is an artifact of my redacting the complete endpoint/path for privacy reasons


> You can try to increase boto3 retries as below. Ultimately I would advice to drill down into the root cause 

Sure, but the reason I am opening this issue is regardless of why the endpoint connection error occurs (i.e. rate-limiting/ insufficient retries) - wrangler's `s3.to_parquet` default behavior (with use_threads=True) should not be a silent failure (i.e. writes a corrupt file that is only discovered later on when someone tries to read the file)

**Closed** 2023-05-14 18:03 UTC
Labels: bug, closing-soon
