### ISSUE TITLE
v3.5 doesn't run on Glue Ray

### ISSUE THREAD

**Issue by bobthemighty** [aws/aws-sdk-pandas#2641] opened 2024-01-24 11:12 UTC
### Describe the bug

When running on Glue Ray, awswrangler fails to import with the following error.

  ```
  File "<stdin>", line 9, in <module>
  File ".../parsers.py", line 1, in <module>
    from src.ingest import io
  File ".../ingest/io.py", line 6, in <module>
    import awswrangler as wr
  File ".../site-packages/awswrangler/__init__.py", line 41, in <module>
    engine.register()
  File ".../site-packages/awswrangler/_distributed.py", line 121, in register
    register_ray()
  File ".../site-packages/awswrangler/distributed/ray/_register.py", line 75, in register_ray
    from awswrangler.distributed.ray.modin.s3._read_orc import _read_orc_distributed
  File ".../site-packages/awswrangler/distributed/ray/modin/s3/_read_orc.py", line 13, in <module>
    from awswrangler.distributed.ray.datasources import ArrowORCDatasource
  File ".../site-packages/awswrangler/distributed/ray/datasources/__init__.py", line 3, in <module>
    from awswrangler.distributed.ray.datasources.arrow_csv_datasink import ArrowCSVDatasink
  File ".../site-packages/awswrangler/distributed/ray/datasources/arrow_csv_datasink.py", line 10, in <module>
    from ray.data.datasource.block_path_provider import BlockWritePathProvider
ModuleNotFoundError: No module named 'ray.data.datasource.block_path_provider'
  ```

The issue is resolved by pinning awswrangler<3.5

Per [the docs](https://docs.aws.amazon.com/glue/latest/dg/edit-script-ray-env-dependencies.html), the deps in a glue environment are:

* boto3 == 1.26.133
* ray == 2.4.0
* pyarrow == 11.0.0
* pandas == 1.5.3
* numpy == 1.24.3
* fsspec == 2023.4.0

### How to Reproduce

* Create a new Ray Glue job with that imports awswrangler
* add awswrangler to the `--pip-install` arg without specifying a version.

### OS

Linux

### Python version

3.9

### AWS SDK for pandas version

3.5

**Comment by jaidisido** [comment] 2024-01-24 11:14
Duplicate of https://github.com/aws/aws-sdk-pandas/issues/2604

**Closed** 2024-01-24 11:15 UTC
Labels: bug
