### ISSUE TITLE
wr.s3.read_parquet() does not perform well on many files

### ISSUE THREAD

**Issue by GeorgeVince** [aws/aws-sdk-pandas#1943] opened 2023-01-12 20:50 UTC
### Describe the bug

I'm trying to coalesce and compress a dataset consisting of many partitions with many files on S3, each partition has roughly 50mb but made up of thousands of files.  

It seems like the performance is not good with `awswrangler` in this particular scenario.

In my dataset it takes roughly 15 seconds to read from s3fs with `pyarrow` but ~300 seconds for `awswrangler`

Below I've compared this to downloading the files locally (and reading with pyarrow), reading them with s3fs with `pyarrow`, and finally reading from s3 with `awswrangler`.

Could be related to: https://github.com/aws/aws-sdk-pandas/issues/644
I've tried running with different values for `use_threads` such as 5, 10, 50 and see no real difference in performance.

### How to Reproduce

```
import s3fs
import pyarrow.parquet as pq
import pandas as pd
import awswrangler as wr
from timeit import timeit

s3 = s3fs.S3FileSystem()

path = "your-bucket/benchmark"

def seed_random_data():
    for x in range(1500):
        data = {'value': [x]}
        df = pd.DataFrame(data)
        wr.s3.to_parquet(df, path=f"s3://{path}/{x}.parquet")

def read_local_test():
    src = 's3://' + path
    dst = '/tmp/debug/'
    s3.get(src, dst, recursive=True)
    table = pq.read_table(dst)


def read_test_pyarrow():
    table = pq.read_table(path, filesystem=s3)


def read_test_wrangler():
    df = wr.s3.read_parquet("s3://" + path)


if __name__ == "__main__":

    seed_random_data()
    print("read_local_test(): ", timeit('read_local_test()', number=1, globals=globals()))
    print("read_test_pyarrow(): ", timeit('read_test_pyarrow()', number=1, globals=globals()))
    print("read_test_wrangler(): ", timeit('read_test_wrangler()', number=1, globals=globals()))
```

```
read_local_test():  7.351257916000001
read_test_pyarrow():  13.115035040999999
read_test_wrangler():  94.643410833
```

### Expected behavior

`awswrangler` should have similar performance to the other methods.

### OS

Mac

### Python version

3.9.6

### AWS SDK for pandas version

```awswrangler         2.19.0```
```pyarrow             10.0.1```

**Comment by kukushking** [comment] 2023-01-13 17:15
Thanks for opening this @GeorgeVince! We do use a custom implementation of S3 fs that is most likely the cause of this. I'll have a look if we can switch to s3fs or pyarrow's impl

**Comment by GeorgeVince** [comment] 2023-01-16 13:27
Thanks @kukushking!

**Comment by jaidisido** [comment] 2023-01-17 09:25
Two things to consider here:
1. The custom S3 fs implementation offers some additional flexibility that is not available in the pyarrow fs. Examples include the ability to filter for specific S3 object version ids or to specify a KMS key id for decryption...
2. The code used for benchmarking is a bit oversimplifying what happens under the hood. For one, the `read_test_pyarrow` returns a pyarrow table when `wr.s3.read_parquet` returns a pandas data frame. Similarly, we perform some type conversion by default (via the `map_types` argument) which is computationally expensive. This is not to say that the current implementation is not slower in any case though

One solution we could consider for our next major version is to simply enable the user to pass the filesystem of their choice. Pyarrow [read_table](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html) itself allows that (see filesystem argument)

**Comment by kukushking** [comment] 2023-01-18 15:46
Thanks @jaidisido, to add to that - the custom S3 fs implementation also breaks down the objects into ranges and fetches each range in a separate thread, which gives significant performance boost on bigger objects. I'm looking for ways to combine the two but the overhead of even just a simple describe operation (creating the client, etc) to be able to tell if the call should be parallelized already adds up to quite a number when processing many small files.

Pyarrow's implementation apart from it's own implementation of the file system, uses `ParquetDataset` that also has it's own improvements.

I do like the idea of being able to support many file system implementations and being able to switch, for example, even for many small files vs big file use cases.

**Comment by kukushking** [comment] 2023-01-27 14:14
Hi @GeorgeVince we've merged a fix that should address above performance issues as well as memory usage problems. Would appreciate if you could give it a try by installing from main:
```
pip uninstall awswrangler -y
pip install git+https://github.com/awslabs/aws-data-wrangler.git@main
```

The times I currently get on my machine are below - you can see wrangler has about the same performance as pyarrow now:
```
read_test_pyarrow():  60.46403377799999
read_test_wrangler():  55.538528068999995
```

**Comment by kukushking** [comment] 2023-02-06 14:29
Closing due to inactivity. Feel free to reopen if required.

**Closed by kukushking** 2023-02-06 14:29 UTC
Labels: bug
